services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-container
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./outlaws.sql:/docker-entrypoint-initdb.d/outlaws.sql
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - docker-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api-python:
    build:
      context: .
      dockerfile: python.dockerfile
    container_name: api-python-container
    ports:
      - "${PYTHON_API_PORT}:${PYTHON_API_PORT}"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DB_URL}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - docker-network

  api-go:
    build:
      context: .
      dockerfile: go.dockerfile
    container_name: api-go-container
    ports:
      - "${GO_API_PORT}:${GO_API_PORT}"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DB_URL}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - docker-network
    
  api-node:
    build:
      context: .
      dockerfile: node.dockerfile
    container_name: api-node-container
    ports:
      - "${NODE_API_PORT}:${NODE_API_PORT}"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DB_URL}
    depends_on:
      - postgres
    networks:
      - docker-network

volumes:
  postgres_data:

networks:
  docker-network:
    driver: bridge
