global:
  scrape_interval: 15s
  evaluation_interval: 15s

  remote_write:
    - url: URL_do_remote_write
      basic_auth:
        username: usu√°rio_do_remote_write
        password: senha_do_remote_write

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']